[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_RUNTIME = "edge"
  NEXT_RUNTIME = "edge"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"